# Generated by Django 5.0.6 on 2025-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='interview_audios/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
